#!/bin/bash

INSTNAME=$1 
ARGV=$2   
INSTROOT=`pwd`   
CWAS_USER="CHANGE_HERE_FOR_WAS_USER"
CWAS_GROUP="CHANGE_HERE_FOR_WAS_GROUP"  
temp_java_home="/etc/alternatives/jre";
INSTDIR=${INSTROOT}/instance/${INSTNAME}
CONFDIR="conf/"  
CONFIG="sia.conf"
CONF=${CONFDIR}${CONFIG}     

function _front()
{ 
    TITLE="CHLUX WEB APPLICATION SERVER INSTANCE MANAGER"
    clear
    eval printf %.0s\# '{1..'${COLUMNS:-$(tput cols)}'}'; echo    
    echo -e "" 
    printf "%*s\n" $(((${#TITLE}+$(tput cols))/2)) "$TITLE"
    echo -e "\t Version : 1.0.2c" 
    echo -e "\t Author  : Chlux Co,Ltd."
    echo -e ""
    eval printf %.0s\# '{1..'${COLUMNS:-$(tput cols)}'}'; echo   
	UNAME=`id -u -n`
 
} 

_footer()
{ 
echo "FOOTER"
} 

# check JAVA_OPT  
_setjavahome()
{
    if [[ ! ${temp_java_home} ]]; then
        echo -n -e "\e[32mEnter JAVA_HOME(JRE) for tomcat (default : \\e[2m${temp_java_home} ) : \e[0m"
        read a
        if [[ $a ]]; then
            temp_java_home=${a}
        else
            echo -e "\e[91mYou should enter JAVA_HOME(JRE)\e[0m"   
            exit;
            #_setjavahome;
        fi
    else
        echo -e "\e[32mTomcat will use this JAVA_HOME : \e[2m${temp_java_home}\e[0m" 
        read -r -p "Continue[Y/n] : " response
        case ${response} in
            [yY][eE][sS]|[yY])
                echo -e "\e[32mTomcat installing ...\e[0m" 
                ;;
            [nN][oO]|[nN])
                temp_java_home=""
                _setjavahome
                ;;
            *)
                echo -n -e "\e[32mEnter JAVA_HOME(JRE) for tomcat (default : \\e[2m${temp_java_home} ) : \e[0m"
                ;;
        esac
    fi
}

_getjavaversion() 
{
    echo -e -n "\e[32mChecking JAVA Version (java : ${temp_java_home}/bin/java -version ):"
    javav=`${temp_java_home}/bin/java -version 2>&1 | head -n 1 | awk -F '"' '{print $2}'`
    echo -e ${javav}"\e[0m" 

    if [ -z ${javav} ]; then
        echo -e "\e[31mWrong JAVA_HOME path, Please check again JAVA_HOME\e[0m"  
        exit;
    fi
}

_setjavaopt()
{
    echo -e "\e[32msetup JAVA_OPTS for ${javav} \e[0m"
   jdk6=$(echo $javav | sed -n '/1.6.0/p')
   jdk7=$(echo $javav | sed -n '/1.7.0/p')
   jdk8=$(echo $javav | sed -n '/1.8.0/p')

    if [ ! -z ${jdk6} ]; then
        #SET JAVA_OPT 
        #echo ${jdk6} 
        #OPT="export \"JAVA_OPTS=\$JAVA_OPTS -Xms128m -Xmx1024m -XX:PermSize=128m -XX:MaxPermSize=1024m\""
        OPT="export \"JAVA_OPTS=\$JAVA_OPTS -Xms1024m -Xmx2048m -XX:PermSize=512m -XX:MaxPermSize=1024m\"" 
    fi

    if [ ! -z ${jdk7} ]; then
        #SET JAVA_OPT
        #echo ${jdk7} 
        #OPT="export \"JAVA_OPTS=\$JAVA_OPTS -server -Xms128m -Xmx512m\""
        OPT="export \"JAVA_OPTS=\$JAVA_OPTS -Xms1024m -Xmx2048m -XX:PermSize=512m -XX:MaxPermSize=1024m\""
    fi

    if [ ! -z ${jdk8} ]; then
        #SET JAVA_OPT
        #echo ${jdk8}
        #OPT="export \"JAVA_OPTS=\$JAVA_OPTS -server -Xms128m -Xmx512m\""
        OPT="export \"JAVA_OPTS=\$JAVA_OPTS -server -Xms1024m -Xmx2048m -XX:MaxMetaspaceSize=1024m -XX:MetaspaceSize=512m\""
        #OPT="export \"JAVA_OPTS=\$JAVA_OPTS -Xms128m -Xmx1024m -XX:PermSize=128m -XX:MaxPermSize=1024m\""
    fi  
	
	FIXEDOPT="export \"JAVA_OPTS=\$JAVA_OPTS -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintHeapAtGC -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=70 -Djava.awt.headless=true -Dcom.sun.management.jmxremote\""
    
    echo -e "export \"JAVA_OPTS=\"\"\""  > .javaopts
	echo -e "export JAVA_HOME=${temp_java_home}" >> .javaopts
    echo -e ${OPT} >> .javaopts 
    echo -e ${FIXEDOPT} >> .javaopts 
}

_setDefault()
{
    shutdownport=8005
    httpport=8080
    httpsport=8443
    redport=${httpsport}
    ajpport=8009
}
addInst() { 

    #INSTROOT=`pwd` 
    #INSTDIR=${INSTROOT}/instance/${INSTNAME}
    #CONFDIR="conf/"  
    #CONFIG="sia.conf"
    #CONF=${CONFDIR}${CONFIG}    
    
    #if [ ! -f .javaopts ]; then  
    #    echo -e "\e[31mCiritical] No file for setup JAVA_OTPS . Please run installer first\e[0m" 
    #    exit;
    #fi  

    if [ -d ${INSTDIR} ]; then  
        echo "Already exist Instance name (${INSTNAME})"
        echo "Exit script" 
        exit
    fi 
 
    echo "iNSTNACE NAME : " ${INSTNAME}""
    echo -n "SERVICE IP :" 
    read sip
    if [[ $sip ]]; then
       serviceip=${sip} 
    fi 
    echo -n "SHUTDOWN PORT (default : 8005) :" 
    read sport
    if [[ $sport ]]; then
       shutdownport=${sport} 
    fi 
    echo -n "HTTP PORT     (default : 8080) :"
    read hport 
    if [[ $hport ]]; then
       httpport=${hport} 
    fi 
    echo -n "HTTPS PORT    (default : 8443) : "
    read hsport
    if [[ $hsport ]]; then
       httpsport=${hsport} 
    fi 
    echo -n "REDIRECT PORT (default : 8443) : "
    read rport
    if [[ $rport ]]; then
      redport=${rport} 
    fi 
    echo -n "AJP PORT      (default : 8009) : "
    read aport 
    if [[ $aport ]]; then
      ajpport=${aport} 
    fi 

    #echo -e "\e[32madd instance ${INSTNAME} \e[0m"
    echo  "Create instance directory : ${INSTNAME}"
    mkdir -p ${INSTDIR}
    mkdir -p ${INSTDIR}/${CONFDIR}
    mkdir -p ${INSTDIR}/lib
    mkdir -p ${INSTDIR}/logs
    mkdir -p ${INSTDIR}/temp
    mkdir -p ${INSTDIR}/work

    cp -r share/conf ${INSTDIR}/.
    cp -r share/webapps ${INSTDIR}/.
   
    echo "Create ${INSTNAME} instance configuration"

    echo -e "#!/bin/bash"  >>                                                       ${INSTDIR}/${CONF}
    echo -e "sia_instname=\"${INSTNAME}\"" >>                                       ${INSTDIR}/${CONF}
    echo -e "sia_shutdown=${shutdownport}" >>                                       ${INSTDIR}/${CONF}
    echo -e "sia_http=${httpport}" >>                                               ${INSTDIR}/${CONF}
    echo -e "sia_https=${httpsport}" >>                                             ${INSTDIR}/${CONF}
    echo -e "sia_redirect=${redport}" >>                                            ${INSTDIR}/${CONF}
    echo -e "sia_ajp=${ajpport} " >>                                                ${INSTDIR}/${CONF}
    echo -e "sia_jvmroute=\"${INSTNAME}\"" >>                                       ${INSTDIR}/${CONF} 
    echo -e "sia_serviceip=\"${serviceip}\"" >>                                       ${INSTDIR}/${CONF} 
   

    cat .javaopts >> ${INSTDIR}/${CONF}
    rm .javaopts  
    #echo -e "export \"JAVA_OPTS=\"\"\""  >> ${INSTDIR}/${CONF}
    echo -e "export \"JAVA_OPTS=\$JAVA_OPTS -Dtomcat.port.shutdown=\$sia_shutdown\""  >>    ${INSTDIR}/${CONF}
    echo -e "export \"JAVA_OPTS=\$JAVA_OPTS -Dtomcat.port.http=\$sia_http\"" >>             ${INSTDIR}/${CONF}
    echo -e "export \"JAVA_OPTS=\$JAVA_OPTS -Dtomcat.port.https=\$sia_https\"" >>           ${INSTDIR}/${CONF}
    echo -e "export \"JAVA_OPTS=\$JAVA_OPTS -Dtomcat.port.redirect=\$sia_redirect\"" >>     ${INSTDIR}/${CONF}
    echo -e "export \"JAVA_OPTS=\$JAVA_OPTS -Dtomcat.port.ajp=\$sia_ajp\"" >>               ${INSTDIR}/${CONF}
    echo -e "export \"JAVA_OPTS=\$JAVA_OPTS -Dtomcat.port.jvmroute=\$sia_jvmroute\"" >>     ${INSTDIR}/${CONF} 
    echo -e "export \"JAVA_OPTS=\$JAVA_OPTS -Dtomcat.port.serviceip=\$sia_serviceip\"" >>     ${INSTDIR}/${CONF} 
   #echo -e "export \"JAVA_OPTS=\$JAVA_OPTS ${OPT}" >> ${INSTDIR}/${CONF} 
    
    #cat .javaopts >> ${INSTDIR}/${CONF}
    cp ${INSTROOT}/share/dist/server.xml.dist ${INSTDIR}/${CONFDIR}/server.xml
    cp ${INSTROOT}/share/dist/server_ha.xml.dist ${INSTDIR}/${CONFDIR}/server_ha.xml
    cp ${INSTROOT}/share/dist/context_ha.xml.dist ${INSTDIR}/${CONFDIR}/context_ha.xml
    cp ${INSTROOT}/share/dist/web_ha.xml.dist ${INSTDIR}/${CONFDIR}/web_ha.xml 
	cp ${INSTROOT}/share/dist/session.jsp ${INSTDIR}/webapps/ROOT/session.jsp


} 
removeInst() {  
    `rm -rf ${INSTDIR}`
}

_confirm()
{ 
    echo "Will you create instance  : ${INSTNAME}" 
    read -r -p "Continue[y/N] : " response
    case ${response} in
            [yY][eE][sS]|[yY])
                echo "Start create ${INSTNAME} instance"
                ;;
            [nN][oO]|[nN]) 
                echo "Exit script" 
                exit
                ;;
            *)  
                echo "Exit script" 
                exit
                ;;
        esac  
}  

_usageprint()
{
    echo "Usage : instmanager [INSTANCE_NAME] {add | remove}" 
    exit
} 
chkOwner()
{
    UNAME=`id -u -n`

    if [ $UNAME != ${CWAS_USER} ]; then
        echo "  Start failure WAS service. WAS control allow to [ ${CWAS_USER} ] user"
        exit
    fi
}

#INSTNAME=$1 
#ARGV=$2   
#INSTROOT=`pwd`   


#temp_java_home="/etc/alternatives/jre";
#INSTDIR=${INSTROOT}/instance/${INSTNAME}
#CONFDIR="conf/"  
#CONFIG="sia.conf"
#CONF=${CONFDIR}${CONFIG}     

chkOwner
if [ "$#" -ne 2 ]; then   
	_usageprint
else 
    _front  
    case $2 in 
    "add" )   
		_confirm
		_setjavahome
		_getjavaversion
		_setjavaopt
        _setDefault 
        addInst 
        ;;
    "remove" )
        removeInst  
        ;; 
	*)
		_usageprint
		exit
    esac 
fi
